function [H,H_siso] = create_chanel(flag_my_chanel,prm)
    switch flag_my_chanel
        case 'STATIC'
            rng(167)
            for i= 1:prm.numTx
                for j = 1:prm.numRx           
                    H(i,j) = (randn(1)+1i*randn(1))/sqrt(2);
                end
            end 
            H_siso = (randn(1)+1i*randn(1))/sqrt(2);
        case 'AWGN'        
            H = eye(prm.numTx,prm.numRx);
            H_siso = 1;
%         case 'BAD'
%             H = zeros(prm.numTx,prm.numRx);
%             H(1,1) = 1.1 - i*1;
%             H(1,2) = 1 - i*1;
%             H(2,1) = -1 - i*1;        
%             H(2,2) = -1 - i*1;
        case 'RAYL' 
            H = comm.MIMOChannel(...
                'SampleRate',                prm.SampleRate,...
                'PathDelays',                prm.tau,...
                'AveragePathGains',          prm.pdB,...
                'MaximumDopplerShift',       0,...
                'SpatialCorrelationSpecification', 'None',... 
                'NumTransmitAntennas',prm.numTx,...
                'NumReceiveAntennas',prm.numRx,...
                'PathGainsOutputPort', true);
%                 'TransmitCorrelationMatrix', cat(3, eye(2), [1 0.01;0.01 1]),...
%                 'ReceiveCorrelationMatrix',  cat(3, [1 0.1;0.1 1], eye(2)),...
            H_siso =  comm.RayleighChannel(...
                'SampleRate',               prm.SampleRate, ...
                'PathDelays',               prm.tau, ...
                'AveragePathGains',         prm.pdB,...
                'MaximumDopplerShift',      0,...
                'PathGainsOutputPort',true);
        case 'RIC'
            H = comm.MIMOChannel(...
                'SampleRate',                prm.SampleRate,...
                'PathDelays',                prm.tau,...
                'AveragePathGains',          prm.pdB,...
                'FadingDistribution',        'Rician',...
                'KFactor',                   prm.KFactor,...
                'DirectPathDopplerShift',    zeros(1,length(prm.KFactor)),...
                'DirectPathInitialPhase',    zeros(1,length(prm.KFactor)),...
                'MaximumDopplerShift',       0,...
                'SpatialCorrelationSpecification', 'None',... 
                'NumTransmitAntennas',prm.numTx,...
                'NumReceiveAntennas',prm.numRx,...
                'PathGainsOutputPort', true);
            
            H_siso =  comm.RicianChannel(...
                'SampleRate',               prm.SampleRate, ...
                'PathDelays',               prm.tau, ...
                'AveragePathGains',         prm.pdB,...
                'KFactor',                   prm.KFactor,...
                'MaximumDopplerShift',      0,...
                'PathGainsOutputPort',true);
        case 'RAYL_SPECIAL'
            H = comm.MIMOChannel(...
                'SampleRate',                prm.SampleRate,...
                'PathDelays',                prm.tau,...
                'AveragePathGains',          prm.pdB,...
                'MaximumDopplerShift',       0,...
                'SpatialCorrelationSpecification', 'None',... 
                'NumTransmitAntennas',prm.numTx,...
                'NumReceiveAntennas',prm.numRx,...
                'RandomStream',             'mt19937ar with seed', ...
                'Seed',prm.SEED,... 
                'PathGainsOutputPort', true);
            
            H_siso =  comm.RayleighChannel(...
                'SampleRate',               prm.SampleRate, ...
                'PathDelays',               prm.tau, ...
                'AveragePathGains',         prm.pdB,...
                'MaximumDopplerShift',      0,...
                'RandomStream',             'mt19937ar with seed', ...
                'Seed',prm.SEED,... 
                'PathGainsOutputPort',true);
            
    end
end    



